function [Jac, Jac_q] = J_(lq)
    q1 = lq(1); q2 = lq(2); q3 = lq(3); q4 = lq(4); l1=lq(5); l2=lq(6); l3=lq(7); l4=lq(8);
   
    Jac_q = zeros(6,4,8);
    Jac   = [-l1*sin(q1) - l2*sin(q1)*cos(q2) - l2*sin(q2)*cos(q1) - l3*(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) - l3*(sin(q1)*cos(q2) + sin(q2)*cos(q1))*cos(q3) - l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (sin(q1)*cos(q2) + sin(q2)*cos(q1))*cos(q3))*cos(q4) - l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) - (sin(q1)*cos(q2) + sin(q2)*cos(q1))*sin(q3))*sin(q4), -l2*sin(q1)*cos(q2) - l2*sin(q2)*cos(q1) - l3*(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) - l3*(sin(q1)*cos(q2) + sin(q2)*cos(q1))*cos(q3) - l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (sin(q1)*cos(q2) + sin(q2)*cos(q1))*cos(q3))*cos(q4) - l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) - (sin(q1)*cos(q2) + sin(q2)*cos(q1))*sin(q3))*sin(q4), -l3*(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) - l3*(sin(q1)*cos(q2) + sin(q2)*cos(q1))*cos(q3) - l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (sin(q1)*cos(q2) + sin(q2)*cos(q1))*cos(q3))*cos(q4) - l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) - (sin(q1)*cos(q2) + sin(q2)*cos(q1))*sin(q3))*sin(q4), -l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (sin(q1)*cos(q2) + sin(q2)*cos(q1))*cos(q3))*cos(q4) - l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) - (sin(q1)*cos(q2) + sin(q2)*cos(q1))*sin(q3))*sin(q4);...
        l1*cos(q1) - l2*sin(q1)*sin(q2) + l2*cos(q1)*cos(q2) + l3*(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) + l3*(-sin(q1)*cos(q2) - sin(q2)*cos(q1))*sin(q3) + l4*(-(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*cos(q3))*sin(q4) + l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*sin(q3))*cos(q4), -l2*sin(q1)*sin(q2) + l2*cos(q1)*cos(q2) + l3*(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) + l3*(-sin(q1)*cos(q2) - sin(q2)*cos(q1))*sin(q3) + l4*(-(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*cos(q3))*sin(q4) + l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*sin(q3))*cos(q4), l3*(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) + l3*(-sin(q1)*cos(q2) - sin(q2)*cos(q1))*sin(q3) + l4*(-(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*cos(q3))*sin(q4) + l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*sin(q3))*cos(q4), l4*(-(-sin(q1)*sin(q2) + cos(q1)*cos(q2))*sin(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*cos(q3))*sin(q4) + l4*((-sin(q1)*sin(q2) + cos(q1)*cos(q2))*cos(q3) + (-sin(q1)*cos(q2) - sin(q2)*cos(q1))*sin(q3))*cos(q4);...
        0, 0, 0, 0;...
        0, 0, 0, 0;...
        0, 0, 0, 0;...
        1, 1, 1, 1];
    
    Jac_q(:,:,1) = [- l4*cos(q1 + q2 + q3 + q4) - l2*cos(q1 + q2) - l1*cos(q1) - l3*cos(q1 + q2 + q3), - l4*cos(q1 + q2 + q3 + q4) - l2*cos(q1 + q2) - l3*cos(q1 + q2 + q3), - l4*cos(q1 + q2 + q3 + q4) - l3*cos(q1 + q2 + q3), -l4*cos(q1 + q2 + q3 + q4);...
                    - l4*sin(q1 + q2 + q3 + q4) - l2*sin(q1 + q2) - l1*sin(q1) - l3*sin(q1 + q2 + q3), - l4*sin(q1 + q2 + q3 + q4) - l2*sin(q1 + q2) - l3*sin(q1 + q2 + q3), - l4*sin(q1 + q2 + q3 + q4) - l3*sin(q1 + q2 + q3), -l4*sin(q1 + q2 + q3 + q4);...
                                                                                 0,                                                                    0,                                                  0,                          0;...
                                                                                 0,                                                                    0,                                                  0,                          0;...
                                                                                 0,                                                                    0,                                                  0,                          0;...
                                                                                 0,                                                                    0,                                                  0,                          0];
    Jac_q(:,:,2) = [ - l4*cos(q1 + q2 + q3 + q4) - l2*cos(q1 + q2) - l3*cos(q1 + q2 + q3), - l4*cos(q1 + q2 + q3 + q4) - l2*cos(q1 + q2) - l3*cos(q1 + q2 + q3), - l4*cos(q1 + q2 + q3 + q4) - l3*cos(q1 + q2 + q3), -l4*cos(q1 + q2 + q3 + q4);...
                     - l4*sin(q1 + q2 + q3 + q4) - l2*sin(q1 + q2) - l3*sin(q1 + q2 + q3), - l4*sin(q1 + q2 + q3 + q4) - l2*sin(q1 + q2) - l3*sin(q1 + q2 + q3), - l4*sin(q1 + q2 + q3 + q4) - l3*sin(q1 + q2 + q3), -l4*sin(q1 + q2 + q3 + q4);...
                                                                    0,                                                                    0,                                                  0,                          0;...
                                                                    0,                                                                    0,                                                  0,                          0;...
                                                                    0,                                                                    0,                                                  0,                          0;...
                                                                    0,                                                                    0,                                                  0,                          0];

    Jac_q(:,:,3) =  [ - l4*cos(q1 + q2 + q3 + q4) - l3*cos(q1 + q2 + q3), - l4*cos(q1 + q2 + q3 + q4) - l3*cos(q1 + q2 + q3), - l4*cos(q1 + q2 + q3 + q4) - l3*cos(q1 + q2 + q3), -l4*cos(q1 + q2 + q3 + q4);...
                      - l4*sin(q1 + q2 + q3 + q4) - l3*sin(q1 + q2 + q3), - l4*sin(q1 + q2 + q3 + q4) - l3*sin(q1 + q2 + q3), - l4*sin(q1 + q2 + q3 + q4) - l3*sin(q1 + q2 + q3), -l4*sin(q1 + q2 + q3 + q4);...
                                                  0,                                                  0,                                                  0,                          0;...
                                                  0,                                                  0,                                                  0,                          0;...
                                                  0,                                                  0,                                                  0,                          0;...
                                                  0,                                                  0,                                                  0,                          0];                                                           
    
     Jac_q(:,:,4) =  [ -l4*cos(q1 + q2 + q3 + q4), -l4*cos(q1 + q2 + q3 + q4), -l4*cos(q1 + q2 + q3 + q4), -l4*cos(q1 + q2 + q3 + q4);...
                       -l4*sin(q1 + q2 + q3 + q4), -l4*sin(q1 + q2 + q3 + q4), -l4*sin(q1 + q2 + q3 + q4), -l4*sin(q1 + q2 + q3 + q4);...
                          0,                          0,                          0,                          0;...
                          0,                          0,                          0,                          0;...
                          0,                          0,                          0,                          0;...
                          0,                          0,                          0,                          0];
                                          
     Jac_q(:,:,5) = [ -sin(q1), 0, 0, 0; cos(q1), 0, 0, 0;0, 0, 0, 0;0, 0, 0, 0;0, 0, 0, 0;0, 0, 0, 0];
     Jac_q(:,:,6) = [ -sin(q1 + q2), -sin(q1 + q2), 0, 0;cos(q1 + q2),  cos(q1 + q2), 0, 0; 0,0, 0, 0; 0, 0, 0, 0;0, 0, 0, 0;0,0, 0, 0];
     Jac_q(:,:,7) = [ -sin(q1 + q2 + q3), -sin(q1 + q2 + q3), -sin(q1 + q2 + q3), 0; cos(q1 + q2 + q3),  cos(q1 + q2 + q3),  cos(q1 + q2 + q3), 0; 0,0,0,0;0, 0, 0, 0;0, 0, 0, 0;0, 0, 0, 0];
     Jac_q(:,:,8) = [ -sin(q1 + q2 + q3 + q4), -sin(q1 + q2 + q3 + q4), -sin(q1 + q2 + q3 + q4), -sin(q1 + q2 + q3 + q4);cos(q1 + q2 + q3 + q4),  cos(q1 + q2 + q3 + q4),  cos(q1 + q2 + q3 + q4),  cos(q1 + q2 + q3 + q4); 0,0,0,0;0, 0, 0, 0;0, 0, 0, 0;0, 0, 0, 0];
end